name: My first Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My first Action"
        
        - name: List files
          run: ls
        
        - name: Read files2
          run: |
            if [ -f "README.md" ]; then
              cat README.md
            else
              echo "README.md does not exist."
            fi